### ISSUE TITLE
Please help to successfully run this script

### ISSUE THREAD

**Issue by munirfromdhaka** [brianjmurrell/Android-push-for-Asterisk#1]
Hello,

Need some description how to setup and run this shell script for asterisk to work for android push notification to work.
 I put FCM key and Asterisk (11) ip and using own Linphone with compiled version. I have no knowledge regarding shell script. I just moved from flexisip for push notification to work for asterisk coz its still not stable. 

Thanks

**Comment by brianjmurrell** [comment]
I'm afraid this is provided "as is", for anyone who might know how to integrate it into Asterisk.  I might one day write up a bunch more of how it all works, but at this time, I'm afraid I don't have the resources to do that.
