### ISSUE TITLE
VoIP Push Script 

### ISSUE THREAD

**Issue by Omid-Mohajerani** [brianjmurrell/Android-push-for-Asterisk#2]
Hi,

Is your script works with IOS 14 as well? I have asterisk as SIP server and I have  problem sending VoIP Push for IOS 14 . As we need to send calll exactly after VoIP push . I write an AGI that sends push and it works but the problem is sending call immediately after the Push . When I send the push sometime it takes 1 second or sometime it takes more . So when I send Call exactly after sending push it cant always answer.

**Comment by brianjmurrell** [comment]
I don't know anything about IOS so I don't know.
