### ISSUE TITLE
script for sip? or pjsip

### ISSUE THREAD

**Issue by pergolafabio** [brianjmurrell/Android-push-for-Asterisk#3]
Hey @brianjmurrell 

Am i correct that your script is based on chan_sip and not pjsip?
I'm unable to find the pn-tok anymore, i'm not sure if it saved again in asterisk?

do you still use your script?

**Comment by brianjmurrell** [comment]
> Am i correct that your script is based on chan_sip and not pjsip?

No.  I use pjsip now and have for a long time.  This script was never functional for chan_sip.

> do you still use your script?

Yes.
